version: '3.3'

services:

  minio:
    image: minio/minio:RELEASE.2023-07-21T21-12-44Z.fips
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=User         #These default to minioadmin | minioadmin
      - MINIO_ROOT_PASSWORD=p4ssw0rd
#      - MINIO_SERVER_URL="http://tudominio.com:9000"  
    volumes:
      - ./minio_data:/data
    command: server --console-address ":9001" /data
    restart: unless-stopped


    
